export const USER_AUTH_REQUEST = "USER_AUTH_REQUEST";
export const USER_AUTH_SUCCESS = "USER_AUTH_SUCCESS";
export const USER_AUTH_FAILED = "USER_AUTH_FAILED";


export const LIST_OF_PICTURE_REQUEST = "LIST_OF_PICTURE_REQUEST";
export const LIST_OF_PICTURE_RESET = "LIST_OF_PICTURE_RESET";
export const LIST_OF_PICTURE_SUCCESS = "LIST_OF_PICTURE_SUCCESS";
export const LIST_OF_PICTURE_FAILED = "LIST_OF_PICTURE_FAILED";
export const UPLOAD_PICTURE_REQUEST = "UPLOAD_PICTURE_REQUEST";
export const UPLOAD_PICTURE_SUCCESS = "UPLOAD_PICTURE_SUCCESS";
export const UPLOAD_PICTURE_FAILED = "UPLOAD_PICTURE_FAILED";